# MaxMCC model

In [1]:
#Calculate locations of 1297 cells using max(MCC).
from sklearn.metrics import matthews_corrcoef as mcc, confusion_matrix, precision_score, accuracy_score
import pickle
import math
import pandas as pd
import numpy as np
import sys
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.metrics import pairwise_distances_argmin
from keras.models import load_model

def my_mcc(list1, list2):
    tn, fp, fn, tp = confusion_matrix(list1, list2).ravel()
    #print(f'tn:{tn}, fp:{fp}, fn:{fn}, tp:{tp}, mcc:{my_mcc}')
    if((tp + fp)*(tp + fn)*(tn + fp)*(tn + fn) == 0):
        return np.float64(0) #np.argwhere doesn't like ints or floats.
    my_mcc = (tp*tn - fp*fn) / math.sqrt( (tp + fp)*(tp + fn)*(tn + fp)*(tn + fn) )
    return(my_mcc)

#Calculate MCC row-wise between two matrices
def MCC(bd, dg):
    #Calculate TN times TP
    TP = np.matmul(dg,bd)
    TN = np.matmul(1 - dg, 1 - bd)
    FP = np.matmul(dg, 1 - bd)
    FN = np.matmul(1 - dg, bd)
    numerator = TN*TP - FP*FN
    denominator = 1/np.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN) + sys.float_info.epsilon)
    MCC = numerator*denominator
    return(MCC)

def diff(first, second):
        second = set(second)
        return [item for item in first if item not in second]

num_situ = 20
glist_60 = ['danr','CG14427','dan','CG43394','ImpL2','Nek2','CG8147','Ama','Btk29A','trn','numb','prd','brk','tsh','pxb','dpn','ftz','Kr','h','eve','Traf4','run','Blimp-1','lok','kni','tkv','MESR3','odd','noc','nub','Ilp4','aay','twi','bmm','hb','toc','rho','CG10479','gt','gk','apt','D','sna','NetA','Mdr49','fj','Mes2','CG11208','Doc2','bun','tll','Cyp310a1','Doc3','htl','Esp','bowl','oc','ImpE2','CG17724','fkh']
glist_20 = ['danr','CG14427','dan','CG43394','ImpL2','Nek2','CG8147','Ama','Btk29A','trn','numb','prd','brk','tsh','pxb','dpn','ftz','Kr','h','eve']
glist_84 = ['aay','Ama','Ance','Antp','apt','Blimp-1','bmm','bowl','brk','Btk29A','bun','cad','CenG1A','CG10479','CG11208','CG14427','CG17724','CG17786','CG43394','CG8147','cnc','croc','Cyp310a1','D','dan','danr','Dfd','disco','Doc2','Doc3','dpn','edl','ems','erm','Esp','E(spl)m5-HLH','eve','exex','fj','fkh','ftz','gk','gt','h','hb','hkb','htl','Ilp4','ImpE2','ImpL2','ken','kni','knrl','Kr','lok','Mdr49','Mes2','MESR3','mfas','Nek2','NetA','noc','nub','numb','oc','odd','peb','prd','pxb','rau','rho','run','sna','srp','tkv','tll','toc','Traf4','trn','tsh','twi','zen','zen2','zfh1']
glist_40 = ['danr','CG14427','dan','CG43394','ImpL2','Nek2','CG8147','Ama','Btk29A','trn','numb','prd','brk','tsh','pxb','dpn','ftz','Kr','h','eve','Traf4','run','Blimp-1','lok','kni','tkv','MESR3','odd','noc','nub','Ilp4','aay','twi','bmm','hb','toc','rho','CG10479','gt','gk']
glist_20_mod = ['danr', 'CG14427', 'dan', 'CG43394', 'ImpL2', 'Nek2', 'CG8147', 'Ama', 'Btk29A', 'trn', 'numb', 'prd', 'brk', 'tsh', 'pxb', 'dpn', 'h', 'Traf4', 'run', 'toc']
#glist_tntp_multiply = ['ImpL2','pxb','trn','tsh','noc','CG10479','h','run','dpn','Traf4','CG43394','CG8147','bun','Btk29A','Kr','Ama','prd','MESR3','ftz','aay','kni','Antp','CG14427','odd','eve','bmm','dan','lok','nub','brk','fj','toc','rho','tkv','Blimp-1','CG11208','Nek2','edl','danr','gt']
#glist_tntp_multiply_20 = ['ImpL2','pxb','trn','tsh','noc','CG10479','h','run','dpn','Traf4','CG43394','CG8147','bun','Btk29A','Kr','Ama','prd','MESR3','ftz','aay']
#glist_numerator_20 = ['ImpL2','noc','run','h','pxb','Traf4','Btk29A','trn','CG8147','bun','tsh','dpn','Ama','prd','aay','CG43394','fj','CG10479','Antp','MESR3']
#glist_mcc_20 = ['run','h','noc','Traf4','pxb','aay','Btk29A','trn','odd','CG43394','bun','dpn','nub','CG10479','CG8147','Antp','ImpL2','kni','eve','CG14427']
#glist_mcc_20b = ['noc', 'zfh1', 'Traf4', 'aay', 'CG11208', 'Antp', 'Ama', 'prd', 'CG10479', 'Kr', 'edl', 'kni', 'CG8147', 'apt', 'nub', 'odd', 'bun', 'ImpL2', 'ftz', 'fj']
#glist_tntp_denominator = ['ems','rau','Esp','mfas','Ance','gk','zfh1','Doc3','bowl','gt','hb','nub','rho','fj','kni','htl','NetA','D','edl','toc','bmm','sna','dpn','Blimp-1','eve','aay','Mes2','twi','Antp','CG11208','Cyp310a1','pxb','Nek2','brk','apt','MESR3','CG10479','tkv','ftz','odd']
#glist_tntp_denominator2 = ['Esp','gk','mfas','hb','rho','gt','D','nub','fj','zfh1','toc','dpn','bmm','kni','Antp','aay','brk','edl','NetA','Blimp-1','Nek2','eve','ftz','pxb','odd','CG11208','apt','MESR3','lok','h','prd','CG10479','twi','numb','bun','tkv','run','Kr','Btk29A']
#glist_tntp_denominator_2_20 = ['Esp','gk','mfas','hb','rho','gt','D','nub','fj','zfh1','toc','dpn','bmm','kni','Antp','aay','brk','edl','NetA','Blimp-1']
#glist_20_tom = ['kni','Ance','brk','cad','eve','fkh','hb','hkb','ImpE2','oc','sna','srp','twi','zen','zfh1','gt','Kr','ftz','tkv','croc']
#glist_20_mi = ['sna', 'twi', 'Cyp310a1', 'htl', 'Mes2', 'rho', 'Ama', 'nub', 'MESR3', 'trn', 'tsh', 'run', 'Antp', 'Mdr49', 'oc', 'brk', 'zfh1', 'CG43394', 'Ance', 'pxb']

bdtnp = pd.read_csv('data/binarized_bdtnp.csv')[glist_20_mod].T #(3039, 84)
#DGE (RNA_seq data) contains cell values for the in-citu genes only.
dge = pd.read_csv('data/dge_binarized_distMap.csv').T #(84, 1297)
dge.reset_index(drop=True, inplace=True)

model = load_model('models/weights-improvement-329-0.88.hdf5') #weights-improvement20-89-0.86.hdf5 20-43054-0.87.hdf5 60-74755-0.89.hdf5
# 20-77-0.92.hdf5 20-90-0.88.hdf5

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [2]:
n = 3039 #n = 8 for 60 and n = 2 for 40 genes. n = 3039 for 20 genes.
ind = {}
mcc = MCC(bdtnp, dge[glist_20_mod])

inx = 0
##for index, row in dge.iterrows():
for row in mcc:
    ##my_list = [my_mcc(bdtnp.iloc[j], row[glist_20]) for j in range(0,3039)]
    row_copy = row.copy()
    row_copy.sort()
    #Select the highest n values
    lis_len = len(np.argwhere(row >= row_copy[-n]))
    if (inx % 100 == 0):
        print(f'({inx},{lis_len})', end="")
    candidates1 = []
    if(lis_len <= 10):
        candidates1 = np.ndarray.flatten(np.argwhere(row >= row_copy[-n])).tolist()

    #Using ANN to select the best ten candidates out of around n. For 60 and 40 genes n < 10 hence we use 10.
    candidates2 = np.ndarray.flatten(np.argwhere(row >= row_copy[-n]))
    candidates2 = diff(candidates2, candidates1)
    pred = model.predict(dge.iloc[inx][np.newaxis,:], batch_size=1, verbose=0)[0]

    bdt = bdtnp.copy().T.iloc[candidates2]
    closest = []
    for i in range(0,10):
    #for i in range(0, 10 - len(candidates1)):
        temp_closest = pairwise_distances_argmin(pred.reshape(1, -1), bdt)
        #Since pairwise_distance_argmin starts from zero (doesn't keep the index of bdt) we have to use candidates.
        bdt.iloc[temp_closest[0]].values[:] = 0
        closest = closest + [candidates2[temp_closest[0]]]

    ind[inx] = candidates1 + closest
    inx += 1
    #if(index>100):
    #    break

#Translate to dataframe
#data_ind = pd.DataFrame(list(ind.items()))
#data_ind.drop([0], axis=1, inplace=True)
df2 = pd.DataFrame()
for key, value in ind.items():
    o_row = pd.DataFrame(value).T.reset_index(drop=True)
    df2 = pd.concat([df2,o_row])
#df2.to_csv(f'maxmcc_{num_situ}.csv')
df_ = df2 + 1
#df_.to_csv(f'maxmcc_{num_situ}_plus_one.csv')

#np.isnan(row[26])
#len_list = np.count_nonzero(~np.isnan(row))

#Test results: count the number of agreements with true labels.
#True lables
pkl_file = open('data/labels.pkl', 'rb')
true_labels = pickle.load(pkl_file)
pkl_file.close()
count = 0
real_count = 0
k = 0

for i,val in true_labels.items():
    real_count = real_count + len(val)
    for j in ind[k]:
        if(j in val):
            count = count + 1
            val = np.setdiff1d(val, j)
    #if(len(val) > 0):
    #    print(f'Cell# {k}: Missing {np.ndarray.flatten(val)}')
    k = k + 1
    #if(k>100):
    #    break
print(f'Count of matched labels: {count}, real labels count: {real_count}')

#[ 205,  207,  235, 3030,  238,  239,  240,  242,  202,  241]
#[130, 131, 133, 166, 167, 168, 169, 170, 198, 199]
#60: Full lists: 30 125, 20 124, 10 121, 40 127,Using ann: 20 104, 30 96, 15 111, 10 119
#40: 20 20/27, 30 17/27, 15 20/27, 10 22/27, 40 14/27
#20: 20 7/27, 30 7/27, 40 8/27, 50 9/27, 60 9/27, 70 10/27, 80 10/27, 90 10/27, 100 10/27, 150 10/27
#20: 65 42/127, 60 42/127, 70 44/127, 75 44/127, 68 43/127
#20: 70 14/27

(0,3039)(100,3039)(200,3039)(300,3039)(400,3039)(500,3039)(600,3039)(700,3039)(800,3039)(900,3039)(1000,3039)(1100,3039)(1200,3039)Count of matched labels: 808, real labels count: 1693

In [8]:
#Using 20 locations from ann model increase the matched labels from 747 to 1003 out of 1693.
#Trying oposite order of models, first ANN and then MAXMCC.
n = 3039 #n = 8 for 60 and n = 2 for 40 genes. n = 3039 for 20 genes.
ind = {}
mcc = MCC(bdtnp, dge[glist_20])

inx = 0
for row in mcc:
    if (inx % 100 == 0):
        print(f'{inx} ', end="")
    pred = model.predict(dge.iloc[inx][np.newaxis,:], batch_size=1, verbose=0)[0]
    bdt = bdtnp.copy().T
    closest = []
    for i in range(0,20):
        temp_closest = pairwise_distances_argmin(pred.reshape(1, -1), bdt)
        #Since pairwise_distance_argmin starts from zero (doesn't keep the index of bdt) we have to use candidates.
        bdt.iloc[temp_closest[0]].values[:] = 0
        closest = closest + [temp_closest[0]]

    #candidates2 = np.ndarray.flatten(np.argwhere(row >= my_list_2[-n]))
    #candidates2 = diff(candidates2, candidates1)
    row_copy = row.copy()[closest]
    #my_list_2.sort()
    #Select the highest n values
    #lis_len = len(np.argwhere(row >= my_list_2[-n]))
    #candidates1 = np.ndarray.flatten(np.argwhere(row >= my_list_2[-n])).tolist()

    #distances = [accuracy_score(temp_row, pred) for index, temp_row in bdtnp.iloc[candidates].iterrows()]
    #top_n_idx = np.argsort(distances)[-10:]
    #closest = candidates[top_n_idx]
    #ind[index] = np.concatenate([np.ndarray.flatten(np.argwhere(my_list >= my_list_2[k])), [closest[j] for j in range(0, num_clus)]])
    
    ind[inx] = closest
    inx += 1
    #if(index>100):
    break

0

"\n#Translate to dataframe\n#data_ind = pd.DataFrame(list(ind.items()))\n#data_ind.drop([0], axis=1, inplace=True)\ndf2 = pd.DataFrame()\nfor key, value in ind.items():\n    o_row = pd.DataFrame(value).T.reset_index(drop=True)\n    df2 = pd.concat([df2,o_row])\n#df2.to_csv(f'maxmcc_{num_situ}.csv')\ndf_ = df2 + 1\n#df_.to_csv(f'maxmcc_{num_situ}_plus_one.csv')\n\n#np.isnan(row[26])\n#len_list = np.count_nonzero(~np.isnan(row))\n\n#Test results: count the number of agreements with true labels.\n#True lables\npkl_file = open('data/labels.pkl', 'rb')\ntrue_labels = pickle.load(pkl_file)\npkl_file.close()\ncount = 0\nreal_count = 0\nk = 0\n\nfor i,val in true_labels.items():\n    real_count = real_count + len(val)\n    for j in ind[k]:\n        if(j in val):\n            count = count + 1\n            val = np.setdiff1d(val, j)\n    #if(len(val) > 0):\n    #    print(f'Cell# {k}: Missing {np.ndarray.flatten(val)}')\n    k = k + 1\n    #if(k>100):\n    #    break\nprint(f'Count of matched labels: {count}, real labels count: {real_count}')\n"

In [10]:
#True value gets a lower MAXMCC score.
print(closest) #Closest values on bdtnp to pred. Since many rows in bdtnp are the same, we might catch the real value only after
# the 10'th location.
# We need the ann model to learn different patterns (different between rows).
row_copy #MaxMCC for that row. It cannot assist since most values are the same.

[94, 90, 125, 127, 128, 161, 130, 131, 133, 166, 167, 168, 169, 170, 198, 199, 200, 201, 202, 203]

array([0.5959596 , 0.50251891, 0.50251891, 0.50251891, 0.50251891,
       0.50251891, 0.69751845, 0.69751845, 0.69751845, 0.69751845,
       0.69751845, 0.69751845, 0.69751845, 0.69751845, 0.69751845,
       0.69751845, 0.69751845, 0.69751845, 0.69751845, 0.69751845])

In [12]:
bdtnp.T.iloc[closest]

,danr,CG14427,dan,CG43394,ImpL2,Nek2,CG8147,Ama,Btk29A,trn,numb,prd,brk,tsh,pxb,dpn,ftz,Kr,h,eve
94,1,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,1,1,0
90,1,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,1,0
125,1,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,1,0
127,1,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,1,0
128,1,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,1,0
161,1,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,1,0
130,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
131,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
133,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
166,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
167,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
168,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
169,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
170,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
198,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
199,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
200,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
201,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
202,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0
203,1,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,1,1,0

## Maximize MCC

In [ ]:
#Other approaches
    
#Using TSNE: select the largest cluster.
#clusters = pd.read_csv('data/3000_pos_with_clusters_20_NN.csv')
#ind[index] = np.ndarray.flatten(np.argwhere(my_list >= my_list_2[-n]))
#c = collections.Counter(clusters.iloc[ind[index]].cluster)
#max_clus = max(c, key=c.get)
#ind[index] = [i for i in ind[index] if clusters.iloc[i].cluster == max_clus]

#Find the index for which the list does not pass 10 elements
#for k in [-9,-8,-7,-6,-5,-4,-3,-2,-1]:
#    lis_len_tmp = len(np.argwhere(my_list >= my_list_2[k]))
#    if (lis_len_tmp < 10):
#        break
#num_clus = k + 10
#print(f'({index},{k})', end="")

"""
#Use Kmeans to select from cells with score in the 10'th place.
results_kmeans = pd.DataFrame()
xg = pd.DataFrame(columns=['xcoord', 'ycoord', 'zcoord'])
if(lis_len_tmp < 10):
    #Exclude indices at place k and up from clustering.
    indic = np.setdiff1d(np.ndarray.flatten(np.argwhere(my_list >= my_list_2[-10])),
                         np.ndarray.flatten(np.argwhere(my_list >= my_list_2[k])))
else:
    #At indices k = -1 we have more than 10 elements.
    indic = np.ndarray.flatten(np.argwhere(my_list >= my_list_2[-1]))
xg = pd.concat([xg, geom.iloc[indic]])

#Using KMeans: Search for ten clusters. Translate to the closest points in geometry file.
km = KMeans(n_clusters=num_clus).fit(xg)
closest = pairwise_distances_argmin(km.cluster_centers_, geom.iloc[indic])
"""

In [ ]:
from sklearn.metrics import matthews_corrcoef as mcc
from sklearn.metrics import confusion_matrix
import pickle
import math
import pandas as pd
import numpy as np
import sys
from itertools import combinations

def my_mcc(list1, list2):
    tn, fp, fn, tp = confusion_matrix(list1, list2).ravel()
    my_mcc = (tp*tn - fp*fn) / math.sqrt( (tp + fp)*(tp + fn)*(tn + fp)*(tn + fn) )
    return(my_mcc)

num_situ = 84
list_of_g = [0] * num_situ

def calc_tn_plus_tp(list1, list2):
    for i in range(0,num_situ):
        if(list1[i] == list2[i]):
            list_of_g[i] = list_of_g[i] + 1

            
glist_60 = ['danr','CG14427','dan','CG43394','ImpL2','Nek2','CG8147','Ama','Btk29A','trn','numb','prd','brk','tsh','pxb','dpn','ftz','Kr','h','eve','Traf4','run','Blimp-1','lok','kni','tkv','MESR3','odd','noc','nub','Ilp4','aay','twi','bmm','hb','toc','rho','CG10479','gt','gk','apt','D','sna','NetA','Mdr49','fj','Mes2','CG11208','Doc2','bun','tll','Cyp310a1','Doc3','htl','Esp','bowl','oc','ImpE2','CG17724','fkh']
glist_40 = ['danr','CG14427','dan','CG43394','ImpL2','Nek2','CG8147','Ama','Btk29A','trn','numb','prd','brk','tsh','pxb','dpn','ftz','Kr','h','eve','Traf4','run','Blimp-1','lok','kni','tkv','MESR3','odd','noc','nub','Ilp4','aay','twi','bmm','hb','toc','rho','CG10479','gt','gk']
glist_84 = ['aay','Ama','Ance','Antp','apt','Blimp-1','bmm','bowl','brk','Btk29A','bun','cad','CenG1A','CG10479','CG11208','CG14427','CG17724','CG17786','CG43394','CG8147','cnc','croc','Cyp310a1','D','dan','danr','Dfd','disco','Doc2','Doc3','dpn','edl','ems','erm','Esp','E(spl)m5-HLH','eve','exex','fj','fkh','ftz','gk','gt','h','hb','hkb','htl','Ilp4','ImpE2','ImpL2','ken','kni','knrl','Kr','lok','Mdr49','Mes2','MESR3','mfas','Nek2','NetA','noc','nub','numb','oc','odd','peb','prd','pxb','rau','rho','run','sna','srp','tkv','tll','toc','Traf4','trn','tsh','twi','zen','zen2','zfh1']

bdtnp = pd.read_csv('data/binarized_bdtnp.csv').T #(3039, 84)
dge = pd.read_csv('data/dge_binarized_distMap.csv').T #(84, 1297)
dge.reset_index(drop=True, inplace=True)
labels = pd.read_csv('data/labels.csv')
labels.drop(['Unnamed: 0'], axis=1, inplace=True)

#comb = combinations([i for i in range(0,84)], 40)
#for tup in comb:
#    print(tup)

#Try sum of correct 1's and correct 0's.
#row in labels.iterrows():
#print(index, ' ', end="")
#dge_row = dge.iloc[index]
#len_list = np.count_nonzero(~np.isnan(label_row))
#for j in range(0,len_list):
#    bdtnp_row = bdtnp.iloc[int(label_row[j])]
#     calc_tntp(dge_row, bdtnp_row)
#bdtnp.columns.get_loc('apt')
#glist_tntp_40 = [37,21,11,12,82,32,26,81,41,50,39,66,44,34,20,69,28,27,2,58,7,73,35,46,10,60,36,24,62,30,83,52,55,61,57,72,68,80,40,78]
#bdtnp.iloc[:,glist_tntp].columns

result = pd.DataFrame()
print('Gene, num cells out of max')
for i in range(0,num_situ):
    glist_83 = glist_84.copy()
    glist_83.remove(glist_84[i])
    bd = bdtnp.loc[glist_83].copy()
    dg = dge[glist_83].copy()
    #Calculate TN times TP
    TP = np.matmul(dg,bd)
    TN = np.matmul(1 - dg, 1 - bd)
    FP = np.matmul(dg, 1 - bd)
    FN = np.matmul(1 - dg, bd)
    numerator = TN*TP - FP*FN
    #dge_pos = dg.sum(axis=1)
    #dge_neg = (1-dg).sum(axis=1)
    #bdtnp_pos = bd.sum(axis=1)
    #bdtnp_neg = (1-bd).sum(axis=1)
    denominator = 1/np.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    MCC = numerator*denominator
    
    cell_ind = 0
    num_outs = 0
    #Using calculation of TN*TP-FN*FP on all 3039 cells, we can check the affect of removing a gene
    #on the 'score': check how many true labels are 'out' of the five max values (max cells).
    #and if the right cell falls below the four largest ones.
    #We look for genes that maximize that number.
    for row in MCC:
        row_2 = row.copy()
        row_2.sort()
        largest_ = np.argwhere(row > row_2[-10])
        len_list = np.count_nonzero(~np.isnan(labels.iloc[cell_ind]))
        for j in range(0,len_list):
            if(not labels.iloc[cell_ind,:len_list][j] in largest_):
                num_outs = num_outs + 1
        cell_ind = cell_ind + 1

    print(f'{glist_84[i]}, {num_outs}')
    result = pd.concat([result, pd.DataFrame({'gene':glist_84[i], 'num_outs':num_outs}, index=[0])])

list(result.sort_values('num_outs', ascending=False).head(20).gene)
#['noc', 'zfh1', 'Traf4', 'aay', 'CG11208', 'Antp', 'Ama', 'prd', 'CG10479', 'Kr', 'edl', 'kni', 'CG8147', 'apt', 'nub', 'odd', 'bun', 'ImpL2', 'ftz', 'fj']

In [30]:
#Find genes that minimize denominator, i.e. when removing them this number increase the most.
#for i in range(0,num_situ):
#    count_den = 0
#    for index, row in labels.iterrows():
#        len_list = np.count_nonzero(~np.isnan(row))
#        for j in range(0,len_list):
#            count_den = count_den + dge_pos[index] * dge_neg[index] * bdtnp_pos[row[j]] * bdtnp_neg[row[j]]
#    results = pd.concat([results, pd.DataFrame({'gene':glist_50[i], 'count_den':count_den}, index=[0])])
#    print(glist_50[i], count_den)
#results.to_csv('genes_tntp_denominator_results.csv')

Gene, count_den

# Maximize mutual information along columns of bdtnp and dge

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import mutual_info_score
from numpy.testing import assert_array_equal
import math

bdtnp = pd.read_csv('data/binarized_bdtnp.csv')
dge = pd.read_csv('data/dge_binarized_distMap_T.csv')
labels = pd.read_csv('data/labels.csv')

"""
X = np.array([[0, 0, 0],
              [1, 1, 0],
              [2, 0, 1],
              [2, 0, 1],
              [2, 0, 1]])
y = np.array([0, 1, 2, 2, 1])

# Here X[:, 0] is the most informative feature, and X[:, 1] is weakly informative.
mi = mutual_info_classif(X, y, discrete_features=True) #array([0.67301167, 0.22314355, 0.39575279])
assert_array_equal(np.argsort(-mi), np.array([0, 2, 1]))
"""

bdtnp_result = pd.DataFrame(columns=bdtnp.columns)
dge_result = pd.DataFrame(columns=dge.columns)
labels['num_nulls'] = labels.isnull().sum(axis=1)

#Maximum locations for a cell in the label file is 6.
for index, row in labels.iterrows():
    for val in row:
        if not math.isnan(val):
            dge_result = pd.concat([dge_result, pd.DataFrame(dge.iloc[index]).T])
            bdtnp_result = pd.concat([bdtnp_result, pd.DataFrame(bdtnp.iloc[int(val)]).T])

result = pd.DataFrame()
for gene in dge_results.columns:
    print(f'Gene: {gene}, mutual info score: {mutual_info_score(bdtnp_result[gene], dge_result[gene])}')
    result = pd.concat([result, pd.DataFrame({'gene':gene, 'mutual_info':mutual_info_score(bdtnp_result[gene], dge_result[gene])}, index=[0])])
#    break
#results.to_csv('data/labels_multiple.csv')

"""
#Feature selection using total sum on columns. Check bdtnp and dge and take their union.
bdtnp = pd.read_csv('data/binarized_bdtnp.csv')
bdtnp.loc['Total'] = bdtnp.sum()
bdtnp.T.to_csv('data/binarized_b.csv')

my_list_b = ['danr','CG14427','dan','CG43394','ImpL2','Nek2','CG8147','Ama','Btk29A','trn','numb','prd','brk','tsh','pxb','dpn','ftz','Kr','h','eve','Traf4','run','Blimp-1','lok','kni','tkv','MESR3','odd','noc','nub','Ilp4','aay','twi','bmm','hb','toc','rho','CG10479','gt','gk','apt','D','sna','NetA','Mdr49','fj','Mes2','CG11208','Doc2','bun','tll','Cyp310a1','Doc3','htl','Esp','bowl','oc','ImpE2','CG17724','fkh']
len(my_list_b)

dge = pd.read_csv('data/dge_binarized_distMap.csv')
dge['Total'] = dge.sum(axis=1)
dge.to_csv('data/dge_binarized_d.csv')
my_list_d = ['bun','Ama','dan','Ilp4','noc','Traf4','trn','ImpL2','h','tsh','CG8147','Btk29A','run','apt','Cyp310a1','CG43394','numb','CG10479','CG11208','tkv','lok','danr','odd','Antp','edl','Kr','aay','Mes2','prd','D','ftz','twi','pxb','Blimp-1','toc','sna','MESR3','CG14427','rho','bmm','Mdr49','brk','knrl','zfh1','fj','dpn','nub','Nek2','eve','NetA','htl','E(spl)m5-HLH','CG17786','kni','srp','bowl','mfas','Doc3','gt','CG17724']
len(list(set(my_list_d) & set(glist_60_tom))) #41
"""

In [ ]:
list(result.sort_values('mutual_info', ascending=False).head(20).gene)
#['sna', 'twi', 'Cyp310a1', 'htl', 'Mes2', 'rho', 'Ama', 'nub', 'MESR3', 'trn', 'tsh', 'run', 'Antp', 'Mdr49', 'oc', 'brk', 'zfh1', 'CG43394', 'Ance', 'pxb']

# Use gene to area to geometry mappings to reduce candidates for a cell

In [78]:
import numpy as np
import pandas as pd

#bdtnp = pd.read_csv('data/binarized_bdtnp.csv')
bdtnp = pd.read_csv('data/bdtnp.csv')
#dge = pd.read_csv('data/dge_binarized_distMap.csv').T.reset_index(drop=True)
dge = pd.read_csv('data/magic_dge.csv')
a2g = pd.read_csv('data/area_to_geometry.csv')
g2a = pd.read_csv('data/gene_to_area.csv')

dict_g2a = {}

for col in g2a.columns:
    for val in g2a[col]:
        dict_g2a[val] = col
#'btd': 'Ant',
#'Idgf1': 'Ven',
#'betaTub60D': 'Ant',
#'wor': 'Ven',

dict_a2g = {'Ant':[], 'Dor':[], 'Lat':[], 'Pos':[], 'Ven':[]}
for index, row in a2g.iterrows():
    dict_a2g[row['V4']].append(index)

In [80]:
gene_areas_counter = {'Ant':0, 'Dor':0, 'Lat':0, 'Pos':0, 'Ven':0}
for col in bdtnp.columns:
    if(col in dict_g2a):
        gene_areas_counter[dict_g2a[col]] += 1

gene_areas_counter

{'Ant': 9, 'Dor': 2, 'Lat': 7, 'Pos': 19, 'Ven': 7}

Sum of all genes is 401 hence the weights for scoring regions are:

Ant: 401/96, Dor: 401/44, Lat:401/41, Pos:401/144, Ven:401/76

In [ ]:
areas = []

for index, row in bdtnp.iterrows():
    gene_areas_counter = {'Ant':0, 'Dor':0, 'Lat':0, 'Pos':0, 'Ven':0}
    for i in range(0, len(row)):
        if(row.index[i] in dict_g2a):
            gene_areas_counter[dict_g2a[row.index[i]]] += row[i]
    
    gene_areas_counter['Ant'] *= (44/9) #(401/96)
    gene_areas_counter['Dor'] *= (44/2) #(401/44)
    gene_areas_counter['Lat'] *= (44/7) #(401/41)
    gene_areas_counter['Pos'] *= (44/19) #(401/144)
    gene_areas_counter['Ven'] *= (44/7) #(401/76)
    #print(gene_areas_counter)
    areas.append(max(gene_areas_counter, key=gene_areas_counter.get))
"""
128up            1.524224
140up            1.275327
14-3-3epsilon    8.565557
"""

In [88]:
#from itertools import groupby
#[len(list(group)) for key, group in groupby(areas)]
import collections

counter = collections.Counter(areas)
counter

#areas[0:50]

Counter({'Dor': 1412, 'Ant': 491, 'Pos': 46, 'Ven': 534, 'Lat': 556})

# Select 20 genes such that most rows in BDTNP_binarized are differnet. This will assist ANN model: provide different values for a row in bdtnp.

In [26]:
import pandas as pd
from itertools import combinations as cs

#temp_ = list(set(glist_84) - set(glist_60))
#list_84 = glist_60 + temp_
list_84 = ['danr', 'CG14427', 'dan', 'CG43394', 'ImpL2', 'Nek2', 'CG8147', 'Ama', 'Btk29A', 'trn', 'numb', 'prd', 'brk', 'tsh', 'pxb', 'dpn', 'ftz', 'Kr', 'h', 'eve', 'Traf4', 'run', 'Blimp-1', 'lok', 'kni', 'tkv', 'MESR3', 'odd', 'noc', 'nub', 'Ilp4', 'aay', 'twi', 'bmm', 'hb', 'toc', 'rho', 'CG10479', 'gt', 'gk', 'apt', 'D', 'sna', 'NetA', 'Mdr49', 'fj', 'Mes2', 'CG11208', 'Doc2', 'bun', 'tll', 'Cyp310a1', 'Doc3', 'htl', 'Esp', 'bowl', 'oc', 'ImpE2', 'CG17724', 'fkh', 'edl', 'ems', 'zen2', 'CG17786', 'zen', 'disco', 'Dfd', 'mfas', 'knrl', 'Ance', 'croc', 'rau', 'cnc', 'exex', 'cad', 'Antp', 'erm', 'ken', 'peb', 'srp', 'E(spl)m5-HLH', 'CenG1A', 'zfh1', 'hkb']
bd = pd.read_csv('data/binarized_bdtnp.csv')[list_84]

inx = 0
previous_size = 0
previous_list = []
for tup in cs(bd.columns, 20):
    temp_bd = bd[list(tup)]
    temp_size = len(temp_bd.groupby(temp_bd.columns.tolist(), as_index=False).size())
    if(temp_size > previous_size):
        print(f'Found new set, size:{temp_size}')
        print(list(tup))
        previous_size = temp_size
        previous_list = list(tup)
    if (inx == 1000):
        break
    inx += 1

Found new set, size:815
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'CG43394', 'CG8147']
Found new set, size:832
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'CG43394', 'D']
Found new set, size:907
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'CG43394', 'dpn']
Found new set, size:931
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'CG43394', 'h']
Found new set, size:945
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'CG43394', 'trn']
Found new set, size:972
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'dpn', 'eve']
Found new set, size:981
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'dpn', 'h']
Found new set, size:1030
['aay', 'Ama', 'Ance', 'Antp', 'apt', 'Blimp-1', 'bmm', 'bowl', 'brk', 'Btk29A', 'bun', 'cad', 'CenG1A', 'CG10479', 'CG11208', 'CG14427', 'CG17724', 'CG17786', 'dpn', 'trn']

In [23]:
len(temp_bd.groupby(temp_bd.columns.tolist(), as_index=False).size().reset_index())

815